### ISSUE TITLE
toString null error

### ISSUE THREAD

**Issue by martyalicante** [barisusakli/nodebb-plugin-dbsearch#15]
24/8 18:43 [4361] - error: TypeError: Cannot call method 'toString' of null
    at Object.module.search (/var/exodef/NodeBB/src/database/mongo/main.js:50:35)
    at Object.search.searchQuery [as method] (/var/exodef/NodeBB/node_modules/nodebb-plugin-dbsearch/index.js:160:6)
    at /var/exodef/NodeBB/src/plugins/hooks.js:89:12
    at /var/exodef/NodeBB/node_modules/async/lib/async.js:269:13
    at iterate (/var/exodef/NodeBB/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/var/exodef/NodeBB/node_modules/async/lib/async.js:162:9)
    at Object.async.reduce (/var/exodef/NodeBB/node_modules/async/lib/async.js:268:15)
    at fireFilterHook (/var/exodef/NodeBB/src/plugins/hooks.js:81:9)
    at Object.Plugins.fireHook (/var/exodef/NodeBB/src/plugins/hooks.js:62:5)
    at Object.search.searchQuery (/var/exodef/NodeBB/src/search.js:458:10)
    at Object.async.parallel.tids (/var/exodef/NodeBB/src/search.js:81:13)
    at /var/exodef/NodeBB/node_modules/async/lib/async.js:580:25
    at /var/exodef/NodeBB/node_modules/async/lib/async.js:122:13
    at _each (/var/exodef/NodeBB/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/var/exodef/NodeBB/node_modules/async/lib/async.js:121:9)
    at _parallel (/var/exodef/NodeBB/node_modules/async/lib/async.js:579:20)
TypeError: Cannot call method 'toString' of null
    at Object.module.search (/var/exodef/NodeBB/src/database/mongo/main.js:50:35)
    at Object.search.searchQuery [as method] (/var/exodef/NodeBB/node_modules/nodebb-plugin-dbsearch/index.js:160:6)
    at /var/exodef/NodeBB/src/plugins/hooks.js:89:12
    at /var/exodef/NodeBB/node_modules/async/lib/async.js:269:13
    at iterate (/var/exodef/NodeBB/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/var/exodef/NodeBB/node_modules/async/lib/async.js:162:9)
    at Object.async.reduce (/var/exodef/NodeBB/node_modules/async/lib/async.js:268:15)
    at fireFilterHook (/var/exodef/NodeBB/src/plugins/hooks.js:81:9)
    at Object.Plugins.fireHook (/var/exodef/NodeBB/src/plugins/hooks.js:62:5)
    at Object.search.searchQuery (/var/exodef/NodeBB/src/search.js:458:10)
    at Object.async.parallel.tids (/var/exodef/NodeBB/src/search.js:81:13)
    at /var/exodef/NodeBB/node_modules/async/lib/async.js:580:25
    at /var/exodef/NodeBB/node_modules/async/lib/async.js:122:13
    at _each (/var/exodef/NodeBB/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/var/exodef/NodeBB/node_modules/async/lib/async.js:121:9)
    at _parallel (/var/exodef/NodeBB/node_modules/async/lib/async.js:579:20)
24/8 18:43 [4361] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.

**Comment by barisusakli** [comment]
Can you post the plugin version and nodebb git hash?

**Comment by martyalicante** [comment]
0.2.14
Node is 0.7.2 , the one with xss fix. dont have exact hash here right now

**Comment by barisusakli** [comment]
Update to nodebb 0.7.3 and 0.2.15 it should be fixed in those versions.
