### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by ogerly** [barisusakli/nodebb-plugin-dbsearch#18]
I have long been a problem that is always a mistake when looking at titles and content.
,
in user tags and everything is ok.

`/search/wien
Unable to execute query: error processing query: ns=1.searchpost limit=30 skip=0 Tree: TEXT : query=wien, language=, tag=NULL Sort: {} Proj: { _id: 0, id: 1 } planner returned error: need exactly one text index for $text query`
### Log:

`28/1 14:51 [4336] - [31merror[39m: [plugins] filter:search.query,  Unable to execute query: error processing query: ns=1.searchpost limit=30 skip=0
Tree: TEXT : query=wien, language=, tag=NULL
Sort: {}
Proj: { _id: 0, id: 1 }
 planner returned error: need exactly one text index for $text query
28/1 14:51 [4336] - [31merror[39m: /search/wien
 MongoError: Unable to execute query: error processing query: ns=1.searchpost limit=30 skip=0
Tree: TEXT : query=wien, language=, tag=NULL
Sort: {}
Proj: { _id: 0, id: 1 }
 planner returned error: need exactly one text index for $text query
    at Function.MongoError.create (/var/www/clients/10/30/web/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/var/www/clients/10/30/web/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:266:34)
    at Callbacks.emit (/var/www/clients/10/30/web/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/var/www/clients/10/30/web/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/var/www/clients/10/30/web/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable`(_stream_readable.js:406:5)``

**Comment by barisusakli** [comment]
Try with the latest version of this plugin and let me know if you are still experiencing this.
