### ISSUE TITLE
error: invalid operator: $search

### ISSUE THREAD

**Issue by nWidart** [barisusakli/nodebb-plugin-dbsearch#23]
Hello,

When trying to use the search function, I am getting this error:

![Search function error screenshot](http://imgur.com/3AgeNX2l.png)

In network tab I see the following:

```
{path: "/api/search/view", error: "invalid operator: $search"}
error
:
"invalid operator: $search"
path
:
"/api/search/view"
```

This is what I have in logs from backend:

```
18/4 12:20 [30903] - [31merror[39m: /api/search/view
 MongoError: invalid operator: $search
    at Function.MongoError.create (/home/forge/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/forge/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:266:34)
    at Callbacks.emit (/home/forge/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/home/forge/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/home/forge/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
18/4 12:20 [30903] - [31merror[39m: [plugins] filter:search.query,  invalid operator: $search
```

Did I miss something ?

Thank you

**Comment by barisusakli** [comment]
What is your mongodb version? You need at least 2.6.

**Comment by nWidart** [comment]
Hello,

Sorry for the late reply, I'm running version `2.4.9`. However I ran `apt-get update` and `apt-get upgrade`, and it still didn't go on the 2.6 version. 
Using ubuntu 14.04

**Comment by nWidart** [comment]
After following upgrade instructions from 2.4 to 2.6, `mongod -version` now returns `db version v2.6.12`.

However, the search still doesn't work. With in the logs:

```
11/5 21:41 [2480] - [31merror[39m: /api/search/test
 MongoError: Unable to execute query: error processing query: ns=0.searchpost limit=50 skip=0
Tree: TEXT : query=test, language=, tag=NULL
Sort: {}
Proj: { _id: 0, id: 1 }
 planner returned error: need exactly one text index for $text query
    at Function.MongoError.create (/home/forge/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/forge/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:266:34)
    at Callbacks.emit (/home/forge/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/home/forge/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/home/forge/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
11/5 21:41 [2480] - [31merror[39m: [plugins] filter:search.query,  Unable to execute query: error processing query: ns=0.searchtopic limit=50 skip=0
Tree: TEXT : query=test, language=, tag=NULL
Sort: {}
Proj: { _id: 0, id: 1 }
 planner returned error: need exactly one text index for $text query
```

**Comment by nWidart** [comment]
I upgraded to the latest version of nodebb, version 1.0.4, and search is now functioning correctly.

Sorry for the trouble.

**Comment by barisusakli** [comment]
No problem glad you figured it out :)
