### ISSUE TITLE
TypeError in reIndexPids

### ISSUE THREAD

**Issue by boomzillawtf** [barisusakli/nodebb-plugin-dbsearch#24]
```
TypeError: callback is not a function
    at reIndexPids (/usr/src/app/node_modules/nodebb-plugin-dbsearch/lib/dbsearch.js:360:11)
    at /usr/src/app/node_modules/nodebb-plugin-dbsearch/lib/dbsearch.js:81:4
    at /usr/src/app/src/database/mongo/hash.js:94:4
    at handleCallback (/usr/src/app/node_modules/mongodb/lib/utils.js:96:12)
    at /usr/src/app/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/usr/src/app/node_modules/mongodb/lib/utils.js:96:12)
    at /usr/src/app/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
    at queryCallback (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
    at Callbacks.emit (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:358:23)
    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:292:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
    at TCP.onread (/usr/src/app/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
13/6 20:51 [126] - error: TypeError: callback is not a function
    at reIndexPids (/usr/src/app/node_modules/nodebb-plugin-dbsearch/lib/dbsearch.js:360:11)
    at /usr/src/app/node_modules/nodebb-plugin-dbsearch/lib/dbsearch.js:81:4
    at /usr/src/app/src/database/mongo/hash.js:94:4
    at handleCallback (/usr/src/app/node_modules/mongodb/lib/utils.js:96:12)
    at /usr/src/app/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/usr/src/app/node_modules/mongodb/lib/utils.js:96:12)
    at /usr/src/app/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
    at queryCallback (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
    at Callbacks.emit (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:358:23)
    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:292:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
    at TCP.onread (/usr/src/app/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
13/6 20:51 [126] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
```

**Comment by barisusakli** [comment]
Thanks, released 1.0.2
