### ISSUE TITLE
Search topics cause NodeBB v1.5.3 restart.

### ISSUE THREAD

**Issue by unbug** [barisusakli/nodebb-plugin-dbsearch#36]
I update NodeBB to v1.5.3 and the search will cause a restart when user star a search, if I clear the search index, it will return empty but won't restart NodeBB, so I have to disable the plugin.

**Comment by barisusakli** [comment]
Please post your nodebb git revision and the stack trace you get when the crash happens.

**Comment by unbug** [comment]
I can't find any related logs. I image is all I got.
![image](https://user-images.githubusercontent.com/799578/29241368-bf3175cc-7faa-11e7-87db-455de4c6fe2a.png)

**Comment by barisusakli** [comment]
I meant the server side logs, they should be in your nodebb installation folder under logs/output.log

**Comment by unbug** [comment]
Thats what I mean. I've clear the log and try the search, but the log file is empty. I have no idea.

**Comment by barisusakli** [comment]
Stop nodebb and then start it with `./nodebb dev` then perform the search and look for any errors in the console window.

**Comment by unbug** [comment]
Here is log, have no idea why there is a null issue.
```
12/8 14:26:34 [5477] - error:  TypeError: Cannot convert undefined or null to object
    at /var/www/wasmrocks/NodeBB/src/search.js:107:11
    at nextTask (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5273:14)
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5280:9)
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:906:16
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:421:16
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5278:29)
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:906:16
    at /var/www/wasmrocks/NodeBB/src/posts/summary.js:85:5
    at nextTask (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5273:14)
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5280:9)
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:906:16
    at fireFilterHook (/var/www/wasmrocks/NodeBB/src/plugins/hooks.js:112:11)
    at Object.Plugins.fireHook (/var/www/wasmrocks/NodeBB/src/plugins/hooks.js:96:4)
    at /var/www/wasmrocks/NodeBB/src/posts/summary.js:82:13
    at nextTask (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5273:14)
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5280:9)
12/8 14:26:34 [5477] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
12/8 14:26:35 [5477] - info: [app] Database connection closed.
12/8 14:26:35 [5477] - info: [app] Web server closed to connections.
12/8 14:26:35 [5477] - info: [app] Shutdown complete.
[cluster] Child Process (5477) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
12/8 14:26:36 [5470] - error:  TypeError: Cannot convert undefined or null to object
    at /var/www/wasmrocks/NodeBB/src/search.js:107:11
    at nextTask (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5273:14)
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5280:9)
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:906:16
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:421:16
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5278:29)
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:906:16
    at /var/www/wasmrocks/NodeBB/src/posts/summary.js:85:5
    at nextTask (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5273:14)
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5280:9)
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:906:16
    at fireFilterHook (/var/www/wasmrocks/NodeBB/src/plugins/hooks.js:112:11)
    at Object.Plugins.fireHook (/var/www/wasmrocks/NodeBB/src/plugins/hooks.js:96:4)
    at /var/www/wasmrocks/NodeBB/src/posts/summary.js:82:13
    at nextTask (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5273:14)
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5280:9)
12/8 14:26:36 [5470] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
12/8 14:26:36 [5470] - info: [app] Database connection closed.
12/8 14:26:36 [5470] - info: [app] Web server closed to connections.
12/8 14:26:36 [5470] - info: [app] Shutdown complete.
[cluster] Child Process (5470) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
12/8 14:26:36 [5547] - verbose: * using configuration stored in: /var/www/wasmrocks/NodeBB/config.json
12/8 14:26:37 [5471] - error:  TypeError: Cannot convert undefined or null to object
    at /var/www/wasmrocks/NodeBB/src/search.js:107:11
    at nextTask (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5273:14)
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5280:9)
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:906:16
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:421:16
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5278:29)
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:906:16
    at /var/www/wasmrocks/NodeBB/src/posts/summary.js:85:5
    at nextTask (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5273:14)
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5280:9)
    at /var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:906:16
    at fireFilterHook (/var/www/wasmrocks/NodeBB/src/plugins/hooks.js:112:11)
    at Object.Plugins.fireHook (/var/www/wasmrocks/NodeBB/src/plugins/hooks.js:96:4)
    at /var/www/wasmrocks/NodeBB/src/posts/summary.js:82:13
    at nextTask (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5273:14)
    at next (/var/www/wasmrocks/NodeBB/node_modules/async/dist/async.js:5280:9)
12/8 14:26:37 [5471] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
12/8 14:26:37 [5471] - info: [app] Database connection closed.
12/8 14:26:37 [5471] - info: [app] Web server closed to connections.
12/8 14:26:37 [5471] - info: [app] Shutdown complete.
[cluster] Child Process (5471) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
12/8 14:26:38 [5557] - verbose: * using configuration stored in: /var/www/wasmrocks/NodeBB/config.json
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
12/8 14:26:38 [5557] - info: Initializing NodeBB v1.5.3
12/8 14:26:38 [5557] - verbose: * using mongo store at 127.0.0.1:27017
12/8 14:26:38 [5557] - verbose: * using themes stored in: /var/www/wasmrocks/NodeBB/node_modules
12/8 14:26:40 [5568] - verbose: * using configuration stored in: /var/www/wasmrocks/NodeBB/config.json
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
12/8 14:26:42 [5547] - verbose: [minifier] utilizing a maximum of 0 additional threads
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
12/8 14:26:42 [5547] - verbose: Checking dependencies for outdated modules
12/8 14:26:42 [5547] - warn: [meta/dependencies] Bundled plugin nodebb-plugin-spam-be-gone not found, skipping dependency check.
12/8 14:26:43 [5547] - warn: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.
12/8 14:26:43 [5557] - verbose: [minifier] utilizing a maximum of 0 additional threads
12/8 14:26:43 [5557] - verbose: Checking dependencies for outdated modules
12/8 14:26:44 [5557] - warn: [meta/dependencies] Bundled plugin nodebb-plugin-spam-be-gone not found, skipping dependency check.
12/8 14:26:44 [5547] - info: [themes] Using theme nodebb-theme-persona
12/8 14:26:44 [5547] - verbose: [plugins] Initializing plugins system
12/8 14:26:44 [5547] - verbose: [plugins] Loaded plugin: nodebb-plugin-dbsearch
12/8 14:26:44 [5547] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-extended
12/8 14:26:44 [5547] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-one
12/8 14:26:44 [5547] - verbose: [plugins] Loaded plugin: nodebb-plugin-google-analytics
```

**Comment by barisusakli** [comment]
I think this is already fixed in core you will havr to git pull

**Comment by unbug** [comment]
@barisusakli Thanks 👍
