### ISSUE TITLE
Error at search settings

### ISSUE THREAD

**Issue by alex1702** [barisusakli/nodebb-plugin-dbsearch#39]
If i click at the settings icon i get this error:
![image with error](https://forum.mediathekview.de/assets/uploads/files/1523452192966-suche.jpg)

i use nodebb 1.8.2

log:
```
2018-04-12T13:26:26.721Z [32715] - [31merror[39m: /search
 TypeError: Cannot read property 'length' of undefined
    at Search.query (/home/nodebb/nodebb/node_modules/redisearch/lib/redis-search.js:58:15)
    at Object.exports.search (/home/nodebb/nodebb/node_modules/nodebb-plugin-dbsearch/lib/redis.js:47:9)
    at Object.search.searchQuery [as method] (/home/nodebb/nodebb/node_modules/nodebb-plugin-dbsearch/lib/dbsearch.js:159:5)
    at /home/nodebb/nodebb/src/plugins/hooks.js:115:12
    at /home/nodebb/nodebb/node_modules/async/dist/async.js:2502:9
    at replenish (/home/nodebb/nodebb/node_modules/async/dist/async.js:998:17)
    at /home/nodebb/nodebb/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (/home/nodebb/nodebb/node_modules/async/dist/async.js:1027:24)
    at /home/nodebb/nodebb/node_modules/async/dist/async.js:1032:16
    at Object.reduce (/home/nodebb/nodebb/node_modules/async/dist/async.js:2501:5)
    at fireFilterHook (/home/nodebb/nodebb/src/plugins/hooks.js:107:9)
    at Object.Plugins.fireHook (/home/nodebb/nodebb/src/plugins/hooks.js:87:4)
    at doSearch (/home/nodebb/nodebb/src/search.js:60:14)
    at pids (/home/nodebb/nodebb/src/search.js:73:6)
    at /home/nodebb/nodebb/node_modules/async/dist/async.js:3866:24
    at replenish (/home/nodebb/nodebb/node_modules/async/dist/async.js:998:17)
```

**Comment by barisusakli** [comment]
Make sure nodebb-plugin-dbsearch version is 0.0.8

**Comment by barisusakli** [comment]
`npm i nodebb-plugin-dbsearch@2.0.15 --save`

**Comment by alex1702** [comment]
Error still exists

**Comment by barisusakli** [comment]
what does `npm ls redisearch` show? It should be 0.0.8

**Comment by barisusakli** [comment]
And you restarted nodebb right?

**Comment by alex1702** [comment]
yes

**Comment by alex1702** [comment]
thx
