### ISSUE TITLE
Changing dbsearch mongodb search schema to use _id fails

### ISSUE THREAD

**Issue by dangerusslee** [barisusakli/nodebb-plugin-dbsearch#49]
Just upgraded to v1.11.0 and when running 

```./nodebb upgrade```

I get the following error

```
OK | 1 script(s) found, 67 skipped
  → [2018/12/26] Changing dbsearch mongodb search schema to use _id...
2018-12-05T14:03:48.388Z [21012] - error: uncaughtException: Cannot find module './src/database'
Error: Cannot find module './src/database'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at Object.<anonymous> (C:\web\nodebb\nodebb\node_modules\nodebb-plugin-dbsearch\lib\dbsearch.js:9:23)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17) {"error":{"code":"MODULE_NOT_FOUND"},"stack":"Error: Cannot find module './src/database'\n    at Function.Module._resolveFilename (module.js:555:15)\n    at Function.Module._load (module.js:482:25)\n    at Module.require (module.js:604:17)\n    at Object.<anonymous> (C:\\web\\nodebb\\nodebb\\node_modules\\nodebb-plugin-dbsearch\\lib\\dbsearch.js:9:23)\n    at Module._compile (module.js:660:30)\n    at Object.Module._extensions..js (module.js:671:10)\n    at Module.load (module.js:573:32)\n    at tryModuleLoad (module.js:513:12)\n    at Function.Module._load (module.js:505:3)\n    at Module.require (module.js:604:17)","exception":true,"date":"Wed Dec 05 2018 09:03:48 GMT-0500 (Eastern Standard Time)","process":{"pid":21012,"uid":null,"gid":null,"cwd":"C:\\web\\nodebb\\nodebb","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v9.3.0","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\web\\nodebb\\nodebb\\src\\cli","upgrade"],"memoryUsage":{"rss":132632576,"heapTotal":110632960,"heapUsed":76735832,"external":18760331}},"os":{"loadavg":[0,0,0],"uptime":221070.2878099},"trace":[{"column":15,"file":"module.js","function":"Module._resolveFilename","line":555,"method":"_resolveFilename","native":false},{"column":25,"file":"module.js","function":"Module._load","line":482,"method":"_load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":604,"method":"require","native":false},{"column":23,"file":"C:\\web\\nodebb\\nodebb\\node_modules\\nodebb-plugin-dbsearch\\lib\\dbsearch.js","function":null,"line":9,"method":null,"native":false},{"column":30,"file":"module.js","function":"Module._compile","line":660,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Module._extensions..js","line":671,"method":".js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":573,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":513,"method":null,"native":false},{"column":3,"file":"module.js","function":"Module._load","line":505,"method":"_load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":604,"method":"require","native":false}]}
```

**Comment by barisusakli** [comment]
What folder are you running the upgrade from?

**Comment by dangerusslee** [comment]
The main nodebb folder, which in my case is 

```
C:\web\nodebb\nodebb
```

**Comment by dangerusslee** [comment]
So is this basically an issue on my end?

**Comment by geferon** [comment]
I'm having this issue as well
